%hidden BG="#1E1E2E"
%hidden FG="#D9E0EE"
%hidden WHITE="#FFFFFF"
%hidden FG_ALT="#6E6C7E"
%hidden BLUE_S="#B5E8E0"
%hidden BLUE="#96CDFB"
%hidden BLUE_ALT="#74C7EC"
%hidden RED="#F28FAD"
%hidden GREEN="#ABE9B3"
%hidden YELLOW="#FAE3B0"
%hidden CYAN="#89DCEB"
%hidden MAGENTA="#F5C2E7"

set -g status on
set -g status-interval 1
set -g status-position top
set -g status-justify left
set -g status-style "bg=$BG,fg=$FG"

set -g status-left-length 100
set -g status-left "#[fg=$BG,bg=$BLUE_ALT,bold] \ue602 #S #[fg=$FG,bg=$BG] "
set -g status-right-length 0
set -g status-right ""

set -g window-status-separator " "
set -g window-status-current-format "#[fg=$BG,bg=$BLUE,bold] #I  #W "
set -g window-status-format "#[fg=$FG,bg=$BG] #I  #W "
set -g window-status-activity-style "fg=$BG,bg=$YELLOW,bold"
set -g window-status-bell-style "fg=$BG,bg=$RED,bold"

set -g pane-border-style "fg=$FG_ALT"
set -g pane-active-border-style "fg=$BLUE"
set -g display-panes-colour "$FG_ALT"
set -g display-panes-active-colour "$BLUE"

set -g message-style "fg=$BG,bg=$BLUE,bold"
set -g message-command-style "fg=$BG,bg=$YELLOW,bold"

set -g mode-style "fg=$BG,bg=$BLUE,bold"
