set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

set -g default-shell /usr/bin/fish
set -g default-command /usr/bin/fish

set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 50000
set -g escape-time 10
set -g focus-events on
setw -g mode-keys vi

source ~/.config/tmux/binds.conf
source ~/.config/tmux/theme.conf
