general.import = ["/home/mds/.config/alacritty/themes/rose-pine.toml"]
general.live_config_reload = true

[font]
size = 9

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Medium"

[terminal.shell]
program = "/bin/tmux"

[window]
opacity = 1

[window.padding]
x = 10
y = 10

[[keyboard.bindings]]
key = "K"
mods = "Alt"
action = "ScrollHalfPageUp"
mode = "~Alt"

[[keyboard.bindings]]
key = "J"
mods = "Alt"
action = "ScrollHalfPageDown"
mode = "~Alt"

[[keyboard.bindings]]
key = "Back"
mods = "Control"
chars = "\u0017"
